
baseURL = "https://lburgazzoli.github.io"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Luca Burgazzoli"
theme =[ "hugo-blog-awesome" ]


[menu]
  [[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = ".: LB :."
  defaultColor = "dark"  
  description = '''
        Yet another software developer.
        Ideas are my own.
        '''
  mainSections = ['posts']
  #toc = true
  goToTop = true # set to false to disable 'go to top' button

[params.author]
  avatar = "avatar.jpg" 
  intro = ".: LB :."
  name = ".: LB :."
  description = '''
        Yet another software developer.
        Ideas are my own.
        '''

[[params.socialIcons]]
name = "github"
url = "https://github.com/lburgazzoli"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/lburgazzoli"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/lucaburgazzoli"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  noHl = false
  style = 'monokai'
  tabWidth = 4


[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


