baseURL = "https://lburgazzoli.github.io"
languageCode = "en-us"
title = ".: LB :."
theme =[ "minimal" ]
disqusShortname = "lburgazzoli-github-io"

[params]
    author = "Luca Burgazzoli"
    description = '''
        Yet another software developer.
        Ideas are my own.
        '''
    githubUsername = "lburgazzoli"
    accent = "black"
    showBorder = true
    backgroundColor = "lightgray"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "monokai"
    highlightLanguages = ["go", "java", "rust", "python", "groovy", "yaml", "ini"]



[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.icon]]
    url = "https://github.com/lburgazzoli/"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/lburgazzoli/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/lucaburgazzoli"
    name = "fab fa-linkedin"
    weight = 3

